"""Data store interface."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, List, Literal, Optional, Protocol, Union

if TYPE_CHECKING:
    from pybpmn_server.datastore.data_objects import BpmnModelData, EventData, InstanceData, ItemData
    from pybpmn_server.interfaces.elements import IDefinition


@dataclass
class FindParams:
    """Parameters for find operations."""

    filter: Optional[Dict[str, Any]] = None
    after: Optional[str] = None
    limit: Optional[int] = None
    sort: Optional[Dict[str, Union[Literal[1], Literal[-1]]]] = None
    projection: Optional[Dict[str, Any]] = None
    last_item: Optional[Dict[str, Any]] = None
    latest_item: Optional[Dict[str, Any]] = None
    get_total_count: Optional[bool] = None


@dataclass
class FindResult:
    """Result of a find operation."""

    data: Optional[List[Any]] = None
    next_cursor: Optional[str] = None
    total_count: Optional[int] = None
    error: Optional[str] = None


class IDataStore(Protocol):
    """Data store interface."""
    db_configuration: Any
    db: Any
    locker: Any

    async def save(self, instance: Any) -> None: ...
    async def save_instance(self, instance: Any) -> None: ...
    async def load_instance(self, instance_id: str) -> Optional[dict[str, Any]]: ...
    async def find_item(self, query: Any) -> ItemData: ...
    async def find_instance(self, query: Any, options: Any) -> InstanceData: ...
    async def find_instances(self, query: Any, option: Any) -> List[InstanceData]: ...
    async def find_items(self, query: Any) -> List[ItemData]: ...
    async def delete_instances(self, query: Optional[Any] = None) -> None: ...
    def install(self) -> Any: ...
    def archive(self, query: Any) -> Any: ...
    async def find(self, params: FindParams) -> FindResult: ...


class IModelsDatastore(Protocol):
    """Model data store interface."""
    async def get(self, query: dict[str, Any]) -> List[Dict[str, Any]]: ...
    async def get_list(self, query: Optional[dict[str, Any]]) -> List[dict[str, Any]]: ...
    async def get_source(self, name: Any) -> str: ...
    async def get_svg(self, name: Any) -> str: ...
    async def save(self, name: Any, bpmn: Any, svg: Optional[Any] = None, owner: Optional[Any] = None) -> bool: ...
    async def load(self, name: Any) -> IDefinition: ...
    async def load_model(self, name: str) -> BpmnModelData: ...
    async def find_events(self, query: Any) -> List[EventData]: ...
    async def rebuild(self, model: Optional[Any] = None) -> None: ...
    async def install(self) -> Any: ...
    async def import_model(self, data: Any) -> Any: ...
    async def save_model(self, model: BpmnModelData) -> bool: ...
    async def delete_model(self, name: Any) -> None: ...
    async def rename_model(self, name: Any, new_name: Any) -> bool: ...
