"""Interfaces for BPMN elements."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional, Protocol, Union

if TYPE_CHECKING:
    from .engine import IItem
    from .enums import ExecutionEvent, ItemStatus, NodeAction


class ILoopBehaviour(Protocol):
    collection: Any

    def is_sequential(self) -> bool: ...
    def is_standard(self) -> bool: ...


class IDefinition(Protocol):
    name: Any
    processes: Dict[Any, Any]
    root_elements: Any
    nodes: Dict[Any, Any]
    flows: List[Any]
    source: Any
    logger: Any
    access_rules: List[Any]

    async def load(self) -> Any: ...
    def get_json(self) -> str: ...
    async def get_definition(self, source: Any) -> Any: ...
    def get_start_node(self) -> INode: ...
    def get_node_by_id(self, id: Any) -> INode: ...


class IElement(Protocol):
    id: Any
    type: Any
    name: Any
    lane: Any
    behaviours: Dict[Any, Any]

    def continue_(self, item: IItem) -> Union[None, Any]: ...  # 'continue' is a keyword in Python
    def describe(self) -> List[List[str]]: ...
    def restored(self, item: IItem) -> None: ...
    def resume(self, item: IItem) -> None: ...
    def has_behaviour(self, name: Any) -> bool: ...
    def get_behaviour(self, name: Any) -> Any: ...
    def add_behaviour(self, name: Any, behaviour: Any) -> None: ...


class IFlow(IElement):
    pass


class INode(IElement):
    name: Any
    process_id: Any
    def_: Any  # 'def' is a keyword in Python
    outbounds: List[Any]
    inbounds: List[Any]
    loop_definition: Optional[ILoopBehaviour]

    async def do_event(self, item: IItem, event: ExecutionEvent, new_status: ItemStatus) -> None: ...
    def enter(self, item: IItem) -> None: ...
    def requires_wait(self) -> bool: ...
    def can_be_invoked(self) -> bool: ...
    async def execute(self, item: IItem) -> Union[NodeAction, None]: ...
    async def continue_(self, item: IItem) -> None: ...
    async def start(self, item: IItem) -> NodeAction: ...
    async def run(self, item: IItem) -> NodeAction: ...
    async def end(self, item: IItem) -> None: ...
    def resume(self, item: IItem) -> None: ...
    def init(self, item: IItem) -> None: ...
    async def get_outbounds(self, item: IItem) -> List[IItem]: ...
